-------------------------------------------------------
-- TABLAS Y COMENTARIOS - DB_DISPONIBILIDAD
-------------------------------------------------------

--  DDL for Table TBL_APLICACION
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" 
   (	"ID_APLICACION" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"APLICACION" VARCHAR2(1000 BYTE), 
	"ID_DET_APLICACION" NUMBER(*,0), 
	"ID_TECNOLOGIA" NUMBER(*,0), 
	"ID_RESPONSABLE" NUMBER(*,0), 
	"ID_CELULA" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"ID_APOYA_VD" NUMBER(*,0), 
	"ID_COMO_APOYA_VD" NUMBER(*,0), 
	"ID_HORA_DESDE" NUMBER(*,0), 
	"ID_TIEMPO_HORA" NUMBER(*,0), 
	"ID_SUBPROCESO" NUMBER(*,0), 
	"ID_ESTADO" NUMBER(*,0), 
	"FECHA_INICIO_OPERACION" DATE, 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_APLICACION" IS 'Identificador único de la aplicación (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."APLICACION" IS 'Nombre de la aplicación';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_DET_APLICACION" IS 'Detalle de la aplicación (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_TECNOLOGIA" IS 'Tecnología asociada (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_RESPONSABLE" IS 'Responsable de la aplicación (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_CELULA" IS 'Célula de desarrollo o mantenimiento (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_CATEGORIA" IS 'Categoría de la aplicación (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_APOYA_VD" IS 'Indicador de si apoya VD (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_COMO_APOYA_VD" IS 'Tipo de apoyo a VD (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_HORA_DESDE" IS 'Hora desde la que está activa (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_TIEMPO_HORA" IS 'Tiempo de operación (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_SUBPROCESO" IS 'Subproceso relacionado (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."ID_ESTADO" IS 'Estado actual de la aplicación (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."FECHA_INICIO_OPERACION" IS 'Fecha en que inicia operaciones';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_APLICACION"."USUARIO_REG" IS 'Usuario que registró la aplicación';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION"  IS 'Tabla que almacena información de las Aplicaciones';
--------------------------------------------------------
--  DDL for Table TBL_CALENDARIO
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" 
   (	"FECHA" DATE, 
	"ANIO" NUMBER(*,0), 
	"NUM_MES" NUMBER(*,0), 
	"MES" VARCHAR2(50 BYTE), 
	"NUM_DIA" NUMBER(*,0), 
	"DIA" VARCHAR2(50 BYTE), 
	"NUM_DIA_ANIO" NUMBER(*,0), 
	"NUM_SEMANA" NUMBER(*,0), 
	"NUM_TRIMESTRE" NUMBER(*,0), 
	"NUM_SEMESTRE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."FECHA" IS 'Identificador único del calendario (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."ANIO" IS 'Año (aaaa)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."NUM_MES" IS 'Numero de mes (1-12)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."MES" IS 'Mes escrito';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."NUM_DIA" IS 'Numero de día en el mes';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."DIA" IS 'Día de la semana escrito (L-D)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."NUM_DIA_ANIO" IS 'Numero del día en el año (1-365)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."NUM_SEMANA" IS 'Numero de semana en el año (1-52)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."NUM_TRIMESTRE" IS 'Numero de trimestre (1-4)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CALENDARIO"."NUM_SEMESTRE" IS 'Numero de Semestre (1-2)';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO"  IS 'Tabla que almacena información del calendario ';
--------------------------------------------------------
--  DDL for Table TBL_CANAL_VENTA_DIGITAL
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL" 
   (	"ID_CANALVD" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CANAL_VENTA_DIGITAL" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL"."ID_CANALVD" IS 'Identificador único de los canales de Venta digital (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL"."CANAL_VENTA_DIGITAL" IS 'Nombre del canal';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL"  IS 'Tabla que almacena información de los canales de Venta digital';
--------------------------------------------------------
--  DDL for Table TBL_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CATEGORIA" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CATEGORIA"."ID_CATEGORIA" IS 'Identificador único de la categoria (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CATEGORIA"."CATEGORIA" IS 'Nombres de las cateogiras (POS Y TIENDA/BACKOFFICE/LOGISTICA)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CATEGORIA"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CATEGORIA"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_CATEGORIA"  IS 'Tabla que almacena información de las categorias (POS Y TIENDA/BACKOFFICE/LOGISTICA)';
--------------------------------------------------------
--  DDL for Table TBL_CELULA
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_CELULA" 
   (	"ID_CELULA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"CELULA_DESAROLLO" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CELULA"."ID_CELULA" IS 'Identificador único de la celula (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CELULA"."CELULA_DESAROLLO" IS 'Nombre de la celula';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CELULA"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_CELULA"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_CELULA"  IS 'Tabla que almacena información de las celulas';
--------------------------------------------------------
--  DDL for Table TBL_DOMINIOS
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS" 
   (	"ID_DOMINIOS" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"DOMINIO_LABEL" VARCHAR2(100 BYTE), 
	"DOMINIO_DESC" VARCHAR2(2000 BYTE), 
	"DOMINIO_ESQUEMA" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_DOMINIOS"."ID_DOMINIOS" IS 'Identificador único del tipo del dominio (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_DOMINIOS"."DOMINIO_LABEL" IS 'Label del dominio';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_DOMINIOS"."DOMINIO_DESC" IS 'Descipción del dominio';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_DOMINIOS"."DOMINIO_ESQUEMA" IS 'Esquema del dominio';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_DOMINIOS"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_DOMINIOS"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS"  IS 'Tabla que almacena información de varios tipos';
--------------------------------------------------------
--  DDL for Table TBL_EMPLEADO
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_EMPLEADO" 
   (	"IDENTIFICACION" NUMBER(*,0), 
	"NOMBRES" VARCHAR2(100 BYTE), 
	"APELLIDOS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_EMPLEADO"."IDENTIFICACION" IS 'Identificador único del empleado (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_EMPLEADO"."NOMBRES" IS 'Nombres del empleado';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_EMPLEADO"."APELLIDOS" IS 'Apellidos del empleado';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_EMPLEADO"  IS 'Tabla que almacena información de los empleados';
--------------------------------------------------------
--  DDL for Table TBL_EQUIPO_RESOLUTOR
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR" 
   (	"ID_EQ_RESOLUTOR" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"EQ_RESOLUTOR" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR"."ID_EQ_RESOLUTOR" IS 'Identificador único del equipo resolutor (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR"."EQ_RESOLUTOR" IS 'Nombre del equipo resolutor';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR"  IS 'Tabla que almacena información del equipo resolutor de la indisponibilidad';
--------------------------------------------------------
--  DDL for Table TBL_INDISPONIBILIDAD
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" 
   (	"ID_INDISPONIBILIDAD" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_APLICACION" NUMBER(*,0), 
	"FECHA_HORA_IND" DATE, 
	"ANIO" NUMBER(*,0), 
	"NUM_MES" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(4000 BYTE), 
	"ID_ESTADO_IND" NUMBER(*,0), 
	"CEDULA_REGISTRO" NUMBER(*,0), 
	"CAUSA" VARCHAR2(4000 BYTE), 
	"FECHA_HORA_SOL" DATE, 
	"ID_EQ_RESOLUTOR" NUMBER(*,0), 
	"SOLUCION" VARCHAR2(4000 BYTE), 
	"ID_UBICACION" NUMBER(*,0), 
	"PESO_UBICACION" NUMBER(10,0), 
	"TIEMPO_IND" TIMESTAMP (6), 
	"TIEMPO_IND_MIN" NUMBER(*,0), 
	"ID_TIPO_INDISPONIBILIDAD" NUMBER(*,0), 
	"FACTOR_IND" NUMBER(10,0), 
	"APLICA_IND_PRV" VARCHAR2(1 BYTE), 
	"ID_PROVEEDOR" NUMBER(*,0), 
	"PROC_INDISPONIBILIDAD" NUMBER(10,0), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE), 
	"FECHA_UPD" DATE, 
	"USUARIO_MOD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."ID_INDISPONIBILIDAD" IS 'Identificador único de la indisponibilidad (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."ID_APLICACION" IS 'Identificador de la aplicación afectada (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."FECHA_HORA_IND" IS 'Fecha y hora en que inició la indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."ANIO" IS 'Año en que ocurrió la indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."NUM_MES" IS 'Número del mes en que ocurrió la indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."DESCRIPCION" IS 'Descripción detallada del incidente de indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."ID_ESTADO_IND" IS 'Estado de la indisponibilidad (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."CEDULA_REGISTRO" IS 'Cédula del usuario que registró la indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."CAUSA" IS 'Causa raíz del incidente de indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."FECHA_HORA_SOL" IS 'Fecha y hora en que se resolvió la indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."ID_EQ_RESOLUTOR" IS 'Identificador del equipo resolutor del incidente (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."SOLUCION" IS 'Descripción de la solución aplicada';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."ID_UBICACION" IS 'Ubicación y participación en la compañia (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."PESO_UBICACION" IS 'Peso asignado a la ubicación para el cálculo de impacto';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."TIEMPO_IND" IS 'Duración de la indisponibilidad (hora inicio - hora fin)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."TIEMPO_IND_MIN" IS 'Duración de la indisponibilidad en minutos';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."ID_TIPO_INDISPONIBILIDAD" IS 'Tipo de indisponibilidad (Total/Parcial/Lentitud) (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."FACTOR_IND" IS 'Factor de impacto de la indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."APLICA_IND_PRV" IS 'Indicador de si aplica para proveedor (S/N)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."ID_PROVEEDOR" IS 'Identificador del proveedor responsable (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."PROC_INDISPONIBILIDAD" IS 'Porcentaje de indisponibilidad asociado al incidente';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."FECHA_UPD" IS 'Fecha de la última actualización del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"."USUARIO_MOD" IS 'Usuario que realizó la última modificación';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD"  IS 'Tabla que almacena información de las indisponibilidades de APLICACIONes';
--------------------------------------------------------
--  DDL for Table TBL_LOG_ERRORES
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_LOG_ERRORES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"FECHA" DATE, 
	"PKG_ERROR" VARCHAR2(200 BYTE), 
	"PRC_ERROR" VARCHAR2(200 BYTE), 
	"COD_ERROR" NUMBER, 
	"DESC_ERROR" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESC_ERROR") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TBL_MACROPROCESO
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_MACROPROCESO" 
   (	"ID_MACROPROCESO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"MACRO_PROCESO" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_MACROPROCESO"."ID_MACROPROCESO" IS 'Identificador único del macroproceso (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_MACROPROCESO"."MACRO_PROCESO" IS 'Nombre del macroproceso';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_MACROPROCESO"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_MACROPROCESO"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_MACROPROCESO"  IS 'Tabla que almacena información de los Macro Procesos';
--------------------------------------------------------
--  DDL for Table TBL_PROCESO
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO" 
   (	"ID_PROCESO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PROCESO" VARCHAR2(100 BYTE), 
	"ID_MACROPROCESO" NUMBER(*,0), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROCESO"."ID_PROCESO" IS 'Identificador único del proceso (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROCESO"."PROCESO" IS 'Nombre del proceso';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROCESO"."ID_MACROPROCESO" IS 'Macroproceso asociado al proceso (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROCESO"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROCESO"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO"  IS 'Tabla que almacena información de los Procesos';
--------------------------------------------------------
--  DDL for Table TBL_PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_PROVEEDOR" 
   (	"ID_PROVEEDOR" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PROVEEDOR" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROVEEDOR"."ID_PROVEEDOR" IS 'Identificador único de cada proveedor (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROVEEDOR"."PROVEEDOR" IS 'Nombre del proveedor';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROVEEDOR"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_PROVEEDOR"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_PROVEEDOR"  IS 'Tabla que almacena información de los proveedores';
--------------------------------------------------------
--  DDL for Table TBL_SUBPROCESO
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" 
   (	"ID_SUBPROCESO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUBPROCESO" VARCHAR2(100 BYTE), 
	"ID_MACROPROCESO" NUMBER(*,0), 
	"ID_PROCESO" NUMBER(*,0), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_SUBPROCESO"."ID_SUBPROCESO" IS 'Identificador único del Subproceso (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_SUBPROCESO"."SUBPROCESO" IS 'Nombre del subproceso';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_SUBPROCESO"."ID_MACROPROCESO" IS 'Macroproceso asociado al subproceso (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_SUBPROCESO"."ID_PROCESO" IS 'Proceso asociado al subproceso (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_SUBPROCESO"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_SUBPROCESO"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO"  IS 'Tabla que almacena información de los Subprocesos';
--------------------------------------------------------
--  DDL for Table TBL_TECNOLOGIA_APLICACION
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION" 
   (	"ID_TECNOLOGIA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TECNOLOGIA" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION"."ID_TECNOLOGIA" IS 'Identificador único de la tecnologia (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION"."TECNOLOGIA" IS 'Nombres de las tecnologias (NUBE/ONPREMISE)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION"  IS 'Tabla que almacena información de las tecnologias (NUBE/ONPREMISE)';
--------------------------------------------------------
--  DDL for Table TBL_TIPO_INDISPONIBILIDAD
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD" 
   (	"ID_TIPO_INDISPONIBILIDAD" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"INDISPONIBILIDAD" VARCHAR2(100 BYTE), 
	"FACTOR" NUMBER(10,0), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD"."ID_TIPO_INDISPONIBILIDAD" IS 'Identificador único del tipo de indisponibilidad (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD"."INDISPONIBILIDAD" IS 'Tipo indisponibilidad (TOTAL/PARCIAL/LENTITUD)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD"."FACTOR" IS 'Factor de la indisponibilidad';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD"  IS 'Tabla que almacena información del tipo de indisponibilidad (TOTAL/PARCIAL/LENTITUD)';
--------------------------------------------------------
--  DDL for Table TBL_TIPO_PROBLEMA
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA" 
   (	"ID_TIPO_PROBLEMA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PROBLEMA" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA"  IS 'Tabla que almacena información del tipo de problema';
--------------------------------------------------------
--  DDL for Table TBL_TIPO_TIENDA
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA" 
   (	"ID_TIPO_TIENDA" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TIPO_TIENDA" VARCHAR2(100 BYTE), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA"."ID_TIPO_TIENDA" IS 'Identificador único de cada tipo de tienda (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA"."TIPO_TIENDA" IS 'Nombre de cada tipo de tienda';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA"  IS 'Tabla que almacena información del tipo de tienda';
--------------------------------------------------------
--  DDL for Table TBL_UBICACIONES
--------------------------------------------------------

  CREATE TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" 
   (	"ID_UBICACION" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"UBICACION" VARCHAR2(100 BYTE), 
	"ID_TIPO_TIENDA" NUMBER(*,0), 
	"TIPO_UBICACION" VARCHAR2(20 BYTE), 
	"PESO" NUMBER(10,0), 
	"FECHA_INS" DATE, 
	"USUARIO_REG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_UBICACIONES"."ID_UBICACION" IS 'Identificador único de la ubicación (PK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_UBICACIONES"."UBICACION" IS 'Nombre o descripción de la ubicación';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_UBICACIONES"."ID_TIPO_TIENDA" IS 'Tipo de tienda asociada a la ubicación (FK)';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_UBICACIONES"."TIPO_UBICACION" IS 'Tipo de ubicación';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_UBICACIONES"."PESO" IS 'Peso asignado a la ubicación para cálculo de impacto';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_UBICACIONES"."FECHA_INS" IS 'Fecha de inserción del registro';
   COMMENT ON COLUMN "DB_DISPONIBILIDAD"."TBL_UBICACIONES"."USUARIO_REG" IS 'Usuario que registró la indisponibilidad';
   COMMENT ON TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES"  IS 'Tabla que almacena información de las ubicaciones de tiendas';
