-------------------------------------------------------
-- DATOS DE PRUEBA (INSERTS) - DB_DISPONIBILIDAD
-------------------------------------------------------

REM INSERTING into DB_DISPONIBILIDAD.TBL_APLICACION
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_CALENDARIO
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_CANAL_VENTA_DIGITAL
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_CATEGORIA
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_CELULA
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_DOMINIOS
SET DEFINE OFF;
Insert into DB_DISPONIBILIDAD.TBL_DOMINIOS (ID_DOMINIOS,DOMINIO_LABEL,DOMINIO_DESC,DOMINIO_ESQUEMA,FECHA_INS,USUARIO_REG) values ('1','a','a','a',to_date('08/10/25','DD/MM/RR'),'s');
Insert into DB_DISPONIBILIDAD.TBL_DOMINIOS (ID_DOMINIOS,DOMINIO_LABEL,DOMINIO_DESC,DOMINIO_ESQUEMA,FECHA_INS,USUARIO_REG) values ('2','b','b','b',to_date('08/10/25','DD/MM/RR'),'s');
Insert into DB_DISPONIBILIDAD.TBL_DOMINIOS (ID_DOMINIOS,DOMINIO_LABEL,DOMINIO_DESC,DOMINIO_ESQUEMA,FECHA_INS,USUARIO_REG) values ('3','b','c','b',to_date('08/10/25','DD/MM/RR'),'c');
REM INSERTING into DB_DISPONIBILIDAD.TBL_EMPLEADO
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_EQUIPO_RESOLUTOR
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_INDISPONIBILIDAD
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_LOG_ERRORES
SET DEFINE OFF;
Insert into DB_DISPONIBILIDAD.TBL_LOG_ERRORES (ID,FECHA,PKG_ERROR,PRC_ERROR,COD_ERROR) values ('1',to_date('08/10/25','DD/MM/RR'),'a','a','1');
Insert into DB_DISPONIBILIDAD.TBL_LOG_ERRORES (ID,FECHA,PKG_ERROR,PRC_ERROR,COD_ERROR) values ('2',to_date('08/10/25','DD/MM/RR'),'PKG_APP_INDISPONIBILIDADES','prc_reg_tbl_dominios','-1400');
REM INSERTING into DB_DISPONIBILIDAD.TBL_MACROPROCESO
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_PROCESO
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_PROVEEDOR
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_SUBPROCESO
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_TECNOLOGIA_APLICACION
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_TIPO_INDISPONIBILIDAD
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_TIPO_PROBLEMA
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_TIPO_TIENDA
SET DEFINE OFF;
REM INSERTING into DB_DISPONIBILIDAD.TBL_UBICACIONES
SET DEFINE OFF;
--------------------------------------------------------
