-------------------------------------------------------
-- CONSTRAINTS (PK/UK y LLAVES FORANEAS) - DB_DISPONIBILIDAD
-------------------------------------------------------

--  Constraints for Table TBL_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CATEGORIA" MODIFY ("CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CATEGORIA" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CATEGORIA" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CATEGORIA" ADD CONSTRAINT "PK_TBL_CATEGORIA" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_LOG_ERRORES
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_LOG_ERRORES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_LOG_ERRORES" ADD CONSTRAINT "PK_LOGERROR_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CALENDARIO
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("NUM_MES" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("MES" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("NUM_DIA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("DIA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("NUM_DIA_ANIO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("NUM_SEMANA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("NUM_TRIMESTRE" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" MODIFY ("NUM_SEMESTRE" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CALENDARIO" ADD CONSTRAINT "PK_TBL_CALENDARIO" PRIMARY KEY ("FECHA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CELULA
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CELULA" MODIFY ("ID_CELULA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CELULA" MODIFY ("CELULA_DESAROLLO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CELULA" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CELULA" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CELULA" ADD CONSTRAINT "PK_TBL_CELULA" PRIMARY KEY ("ID_CELULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_INDISPONIBILIDAD
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD" MODIFY ("ID_TIPO_INDISPONIBILIDAD" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD" MODIFY ("INDISPONIBILIDAD" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD" MODIFY ("FACTOR" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD" ADD CONSTRAINT "PK_TBL_TIPO_INDISPONIBILIDAD" PRIMARY KEY ("ID_TIPO_INDISPONIBILIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_MACROPROCESO
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_MACROPROCESO" MODIFY ("ID_MACROPROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_MACROPROCESO" MODIFY ("MACRO_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_MACROPROCESO" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_MACROPROCESO" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_MACROPROCESO" ADD CONSTRAINT "PK_TBL_MACROPROCESO" PRIMARY KEY ("ID_MACROPROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CANAL_VENTA_DIGITAL
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL" MODIFY ("ID_CANALVD" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL" MODIFY ("CANAL_VENTA_DIGITAL" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_CANAL_VENTA_DIGITAL" ADD CONSTRAINT "PK_TBL_CANAL_VENTA_DIGITAL" PRIMARY KEY ("ID_CANALVD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_SUBPROCESO
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" MODIFY ("ID_SUBPROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" MODIFY ("SUBPROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" MODIFY ("ID_MACROPROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" ADD CONSTRAINT "PK_TBL_SUBPROCESO" PRIMARY KEY ("ID_SUBPROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PROCESO
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO" MODIFY ("ID_PROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO" MODIFY ("PROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO" MODIFY ("ID_MACROPROCESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO" ADD CONSTRAINT "PK_TBL_PROCESO" PRIMARY KEY ("ID_PROCESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_PROBLEMA
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA" MODIFY ("ID_TIPO_PROBLEMA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA" MODIFY ("PROBLEMA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_PROBLEMA" ADD CONSTRAINT "PK_TBL_TIPO_PROBLEMA" PRIMARY KEY ("ID_TIPO_PROBLEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TIPO_TIENDA
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA" MODIFY ("ID_TIPO_TIENDA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA" MODIFY ("TIPO_TIENDA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA" ADD CONSTRAINT "PK_TBL_TIPO_TIENDA" PRIMARY KEY ("ID_TIPO_TIENDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_UBICACIONES
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" MODIFY ("ID_UBICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" MODIFY ("UBICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" MODIFY ("ID_TIPO_TIENDA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" MODIFY ("TIPO_UBICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" MODIFY ("PESO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" ADD CONSTRAINT "PK_TBL_UBICACIONES" PRIMARY KEY ("ID_UBICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_EMPLEADO
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EMPLEADO" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EMPLEADO" MODIFY ("NOMBRES" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EMPLEADO" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EMPLEADO" ADD CONSTRAINT "PK_TBL_EMPLEADO" PRIMARY KEY ("IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DOMINIOS
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS" MODIFY ("ID_DOMINIOS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS" MODIFY ("DOMINIO_LABEL" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS" MODIFY ("DOMINIO_DESC" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS" MODIFY ("DOMINIO_ESQUEMA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_DOMINIOS" ADD CONSTRAINT "PK_TBL_DOMINIOS" PRIMARY KEY ("ID_DOMINIOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_INDISPONIBILIDAD
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("ID_INDISPONIBILIDAD" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("ID_APLICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("FECHA_HORA_IND" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("ID_ESTADO_IND" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("CEDULA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("CAUSA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("SOLUCION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("ID_UBICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("FECHA_UPD" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" MODIFY ("USUARIO_MOD" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" ADD CONSTRAINT "PK_TBL_INDISPONIBILIDAD" PRIMARY KEY ("ID_INDISPONIBILIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROVEEDOR" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROVEEDOR" MODIFY ("PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROVEEDOR" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROVEEDOR" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROVEEDOR" ADD CONSTRAINT "PK_TBL_PROVEEDOR" PRIMARY KEY ("ID_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_EQUIPO_RESOLUTOR
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR" MODIFY ("ID_EQ_RESOLUTOR" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR" MODIFY ("EQ_RESOLUTOR" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_EQUIPO_RESOLUTOR" ADD CONSTRAINT "PK_TBL_EQUIPO_RESOLUTOR" PRIMARY KEY ("ID_EQ_RESOLUTOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TECNOLOGIA_APLICACION
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION" MODIFY ("ID_TECNOLOGIA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION" MODIFY ("TECNOLOGIA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION" ADD CONSTRAINT "PK_TBL_TECNOLOGIA_APLICACION" PRIMARY KEY ("ID_TECNOLOGIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_APLICACION
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_APLICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("APLICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_DET_APLICACION" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_TECNOLOGIA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_RESPONSABLE" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_CELULA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_APOYA_VD" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_COMO_APOYA_VD" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_HORA_DESDE" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("ID_TIEMPO_HORA" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("FECHA_INS" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" MODIFY ("USUARIO_REG" NOT NULL ENABLE);
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "PK_TBL_APLICACION" PRIMARY KEY ("ID_APLICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_APLICACION
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_TECNOLOGIA_APLICACION" FOREIGN KEY ("ID_TECNOLOGIA")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_TECNOLOGIA_APLICACION" ("ID_TECNOLOGIA") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_EMPLEADO" FOREIGN KEY ("ID_RESPONSABLE")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_EMPLEADO" ("IDENTIFICACION") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_CELULA" FOREIGN KEY ("ID_CELULA")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_CELULA" ("ID_CELULA") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_APOYA_VD" FOREIGN KEY ("ID_APOYA_VD")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_DOMINIOS" ("ID_DOMINIOS") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_COMO_APOYA" FOREIGN KEY ("ID_COMO_APOYA_VD")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_DOMINIOS" ("ID_DOMINIOS") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_HORA_DESDE" FOREIGN KEY ("ID_HORA_DESDE")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_DOMINIOS" ("ID_DOMINIOS") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_TIEMPO_HORA" FOREIGN KEY ("ID_TIEMPO_HORA")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_DOMINIOS" ("ID_DOMINIOS") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_SUBPROCESO" FOREIGN KEY ("ID_SUBPROCESO")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" ("ID_SUBPROCESO") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_APLICACION" ADD CONSTRAINT "FK_TBL_APLICACION_TBL_ESTADO" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_DOMINIOS" ("ID_DOMINIOS") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_INDISPONIBILIDAD
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" ADD CONSTRAINT "FK_TBL_INDISPONIBILIDAD_TBL_APLICACION" FOREIGN KEY ("ID_APLICACION")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_APLICACION" ("ID_APLICACION") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" ADD CONSTRAINT "FK_TBL_INDISPONIBILIDAD_TBL_DOMINIOS" FOREIGN KEY ("ID_ESTADO_IND")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_DOMINIOS" ("ID_DOMINIOS") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" ADD CONSTRAINT "FK_TBL_INDISPONIBILIDAD_TBL_EMPLEADO" FOREIGN KEY ("CEDULA_REGISTRO")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_EMPLEADO" ("IDENTIFICACION") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" ADD CONSTRAINT "FK_TBL_INDISPONIBILIDAD_TBL_UBICACIONES" FOREIGN KEY ("ID_UBICACION")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_UBICACIONES" ("ID_UBICACION") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" ADD CONSTRAINT "FK_TBL_INDISPONIBILIDAD_TBL_TIPO_INDISPONIBILIDAD" FOREIGN KEY ("ID_TIPO_INDISPONIBILIDAD")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_TIPO_INDISPONIBILIDAD" ("ID_TIPO_INDISPONIBILIDAD") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_INDISPONIBILIDAD" ADD CONSTRAINT "FK_TBL_INDISPONIBILIDAD_TBL_PROVEEDOR" FOREIGN KEY ("ID_PROVEEDOR")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_PROVEEDOR" ("ID_PROVEEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PROCESO
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_PROCESO" ADD CONSTRAINT "FK_TBL_PROCESO_TBL_MACROPROCESO" FOREIGN KEY ("ID_MACROPROCESO")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_MACROPROCESO" ("ID_MACROPROCESO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_SUBPROCESO
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" ADD CONSTRAINT "FK_TBL_SUBPROCESO_TBL_MACROPROCESO" FOREIGN KEY ("ID_MACROPROCESO")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_MACROPROCESO" ("ID_MACROPROCESO") ENABLE;
  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_SUBPROCESO" ADD CONSTRAINT "FK_TBL_SUBPROCESO_TBL_PROCESO" FOREIGN KEY ("ID_PROCESO")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_PROCESO" ("ID_PROCESO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_UBICACIONES
--------------------------------------------------------

  ALTER TABLE "DB_DISPONIBILIDAD"."TBL_UBICACIONES" ADD CONSTRAINT "FK_TBL_UBICACIONES_TBL_TIPO_TIENDA" FOREIGN KEY ("ID_TIPO_TIENDA")
	  REFERENCES "DB_DISPONIBILIDAD"."TBL_TIPO_TIENDA" ("ID_TIPO_TIENDA") ENABLE;
